
eureka: 
  instace:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
spring:
  rabbitmq:
    host: 192.168.1.244 
    port: 5672
    username: guest
    password: guest
