server:
  port: 8888
spring:
  application:
    name: cloud-consumer 
eureka: 
  instace:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #去哪里注册，eureka服务地址